name: eats
description: "SpaceEats app for demo"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # box
  flutter_screenutil:

  # path
  path_provider:

  # svg
  flutter_svg:

  # router
  go_router:

  # database
  sqflite:

  # state management
  flutter_bloc:
  provider:

  # upgrader
  upgrader:
  google_fonts:
  equatable:
  get_it:
  hive:
  thanos_snap_effect:
  easy_localization:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/translations/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

